version: "3.8"

services:
  # React Build Service
  react-build:
    build:
      context: ./yytermi_react
      dockerfile: Dockerfile # Builds the React app
    container_name: react-build
    volumes:
      - ./yytermi_react:/app    # Mount React app code
      - ./yytermi_react/dist:/app/dist # Output the build files

  # NGINX Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80" # Use 8080 for testing
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX config
      - ./yytermi_react/dist:/usr/share/nginx/html:ro # Serve React build files
    depends_on:
      - react-build
    restart: unless-stopped
