version: "3.8"

services:
  # React App Service
  react-app:
    image: ${REACT_IMAGE_URL} # Placeholder for ECR image URL
    container_name: react-app
    restart: always

  # NGINX Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX config
      - certbot-etc:/etc/letsencrypt           # SSL certificates
      - certbot-var:/var/lib/letsencrypt       # Certbot challenges
    depends_on:
      - react-app
    restart: always

  # Certbot Service (Optional, for SSL)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  certbot-etc:
  certbot-var:
