http {
    # First server block
    server {
        listen 80;
        server_name yytermi.co.il www.yytermi.co.il 3.232.146.117;

        location /.well-known/acme-challenge/ {
            root /var/lib/letsencrypt;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Second server block
    server {
        listen 443 ssl;
        server_name yytermi.co.il www.yytermi.co.il 34.196.213.79;

        ssl_certificate /etc/letsencrypt/live/yytermi.co.il/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yytermi.co.il/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/yytermi.co.il/chain.pem;

        location / {
            proxy_pass http://wordpress:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
